services:
  hub:
    container_name: caesaraihub
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  cloudflared:
    extends:
      file: ./CaesarAICloudFlare/docker-compose.yml
      service: cloudflared
  jackett:
    extends:
      file: ./CaesarAIJackett/docker-compose.yml
      service: jackett
  redis:
    extends:
      file: ./CaesarAIRedis/docker-compose.yml
      service: redis
  postgres:
    extends:
      file: ./CaesarAIPostgreSQL/docker-compose.yml
      service: postgres
  celery_worker:
    extends:
      file: ./CaesarAICelery/docker-compose.yml
      service: celery_worker
  prowlarr:
    extends:
      file: ./CaesarAIProwlarr/docker-compose.yml
      service: prowlarr
  musicstreaming:
    extends:
      file: ./CaesarAIMusicStreamYT/docker-compose.yml
      service: musicstreaming
  musicstreamrecommendation:
    extends:
      file: ./CaesarAIMusicRecommendation/docker-compose.yml
      service: musicstreamrecommendation
  moviestreaming:
    extends:
      file: ./CaesarAIMovieStream/docker-compose.yml
      service: moviestreaming

  gamestreaming:
    extends:
      file: ./CaesarAIGameStream/docker-compose.yml
      service: gamestreaming

volumes:
  redis-data:  
  postgres_data:
    driver: local

  

     



      

