services:
  hub:
    container_name: caesaraihub
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  cloudflared:
    extends:
      file: ./CaesarAICloudFlare/docker-compose.yml
      service: cloudflared
  jackett:
    extends:
      file: ./CaesarAIJackett/docker-compose.yml
      service: jackett
  redis:
    extends:
      file: ./CaesarAIRedis/docker-compose.yml
      service: redis
  prowlarr:
    extends:
      file: ./CaesarAIProwlarr/docker-compose.yml
      service: prowlarr
  musicstreaming:
    extends:
      file: ./CaesarAIMusicStreamYT/docker-compose.yml
      service: musicstreaming
  moviestreaming:
    extends:
      file: ./CaesarAIMovieStream/docker-compose.yml
      service: moviestreaming
# Declare the volume at the bottom of the file
volumes:
  redis-data:  

     



      

