version: '3.8'

services:
  redis:
    image: redis
    container_name: some-redis
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # Use the named volume redis-data

# Declare the volume at the bottom of the file
volumes:
  redis-data:  # Declare redis-data volume here
