services:
  jackett:
    extends:
      file: ../CaesarAIJackett/docker-compose.yml
      service: jackett
  prowlarr:
    extends:
      file: ../CaesarAIProwlarr/docker-compose.yml
      service: prowlarr
  redis:
    extends:
      file: ../CaesarAIRedis/docker-compose.yml
      service: redis
  worker:
    build: .
    container_name: celery_worker
    command: celery -A CaesarAICelery.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  moviestreaming:
    depends_on:
      - jackett
      - prowlarr # Optional
    container_name: caesaraimoviestream
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - .:/app

