services:
  jackett:
    extends:
      file: ../CaesarAIJackett/docker-compose.yml
      service: jackett
  prowlarr:
    extends:
      file: ../CaesarAIProwlarr/docker-compose.yml
      service: prowlarr
  redis:
    extends:
      file: ../CaesarAIRedis/docker-compose.yml
      service: redis
  celery_worker:
    extends:
      file: ../CaesarAICelery/docker-compose.yml
      service: celery_worker
    depends_on:
      - redis
      - moviestreaming
  moviestreaming:
    depends_on:
      - jackett
      - prowlarr # Optional
    container_name: caesaraimoviestream
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - .:/app
  cloudflared:
    extends:
      file: ../CaesarAICloudFlare/docker-compose.yml
      service: cloudflared

volumes:
  redis-data:  
  postgres_data:
    driver: local
