services:
  jackett:
    extends:
      file: ../CaesarAIJackett/docker-compose.yml
      service: jackett
  prowlarr:
    extends:
      file: ../CaesarAIProwlarr/docker-compose.yml
      service: prowlarr
  redis:
    extends:
      file: ../CaesarAIRedis/docker-compose.yml
      service: redis
  celery_worker:
    depends_on:
      - redis
      - moviestreaming
  moviestreaming:
    depends_on:
      - jackett
      - prowlarr # Optional
    container_name: caesaraimoviestream
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - .:/app

