services:
  musicstreaming:
    container_name: caesaraimusicstreamyt
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app   
      - /usr/bin/firefox:/usr/bin/firefox:ro
      - /home/amari/.mozilla/firefox/:/home/user/.mozilla/firefox:ro

